Trovi 2.0: Implement native create/edit form
ChameleonCloud/jupyterlab-chameleon pull request #15
Opened 2022-03-02 23:30 UTC by super-cooper

The changes here are quite hefty, but there are still a couple things that don't work. 

* Ownership does not resolve properly. It used to work by looking up an artifact by path, but now that is not possible. I am unsure of the best way to get an artifact UUID to where ownership is determined. 
* I have implemented versioning, but have not tested it because ownership is not properly resolved. It was very simple to implement, similar to how the create calls are generated.
* Update has not been implemented yet. The form is set up such that it will be easy to edit/create a new version by reusing the same form, and it can be done at the same time. The only work is to format edits into JSON patches. Luckily, this is very simple to do with [this library](https://www.npmjs.com/package/rfc6902)

2022-03-02 23:37 UTC, super-cooper commented
![](https://github.trello.services/images/mini-trello-icon.png) [Trovi 2.0: Implement native create/edit form](https://trello.com/c/mXzig1D6/2543-trovi-20-implement-native-create-edit-form)

2022-03-03 22:56 UTC, diurnalist requested changes
We can't drop the sqlite DB, it's the thing that binds the local server state (artifacts checked out to paths on the file system) to Trovi API state (artifact UUIDs). Other than that this is looking pretty good!

The sqlite DB is also the thing that ensures when you load the app, the filesystem icons turn green for folders that are linked to an artifact. It also ensures that when you refresh, the menu options are accurate (e.g., if I publish, then come back a day later, the options should understand it's "edit" or "new version".)

2022-03-03 22:56 UTC, diurnalist commented on jupyterlab_chameleon/artifact.py
> +from dataclasses import asdict
OK, just ensure we depend on Python >= 3.7 explicitly for this

2022-03-03 22:56 UTC, diurnalist commented on jupyterlab_chameleon/artifact.py
> +    """A shared experiment/research artifact that can be spawned in JupyterHub.
Docstring doesn't line up w/ implementation. TBH I don't think you really need documentation here, it's not a library, rather it is adapting a Trovi API object, if anything you could link to Trovi docs?

That said, you already have them, and they're useful for code inspection 👍🏻

2022-03-03 22:56 UTC, diurnalist commented on jupyterlab_chameleon/artifact.py
> +        # Only the deposition information is required. Theoretically this can
Not sure how this comment relates to the exception, is this old text?

2022-03-03 22:56 UTC, diurnalist commented on jupyterlab_chameleon/artifact.py
> +                "content-type": "application/json",
content-type is not JSON for an upload, won't it be a binary upload of a tarball?

2022-03-03 22:56 UTC, diurnalist commented on src/artifact-sharing/widget.tsx
> +    return this.props.artifact.id === null || this.props.artifact.id === undefined;
```suggestion
    return !this.props.artifact.id;
```

2022-03-30 01:41 UTC, merged