Ux fixes
ChameleonCloud/jupyterlab-chameleon pull request #34
Opened 2023-03-27 16:31 UTC by Mark-Powers

- Artifacts are read from the sqlite3 database and all .trovi.json files. This allows users to move around and rename folders, and they will still be linked to the artifact.
- Creates a "Link" widget where a user can link a directory to an existing trovi artifact, allowing them to create new versions and edit metadata for artifacts they may have imported via upload or git (or in directories that were moved/renamed)
- Allows users to install their own lab extensions via the manager sidebar. 
- Installs the git lab extension by default
- Adds a dev mode for our lab extension

This also includes a major refactor of `widgets.tsx` into individual component files (most things under `src/artifact-sharing/components/`) to help make this code more maintainable.

2023-03-27 21:19 UTC, super-cooper requested changes
The code looks much more readable now, and I'm very happy to see some long-awaited changes in here. There are a few errors, as well as some places I'm wondering whether we can further free ourselves from legacy.

2023-03-27 21:19 UTC, super-cooper commented on src/artifact-sharing/components/new-artifact-text.tsx
> +            href="https://chameleoncloud.readthedocs.io"
https://chameleoncloud.readthedocs.io/en/latest/technical/sharing.html

2023-03-27 21:20 UTC, super-cooper commented on jupyterlab_chameleon/db.py
>      id: str
Even better, we don't need `deposition_repo` at all because we can use `/artifacts/<uuid>/versions/<slug>/contents`

2023-03-28 16:02 UTC, Mark-Powers commented on jupyterlab_chameleon/db.py
>      id: str
I'm just removing comments from this file, and leaving it as is, since the entire `db.py` file is legacy at this point.

2023-03-29 14:42 UTC, super-cooper approved these changes
Looks good! If I understand the changes correctly:

The initial UUID/slug is passed to the lab via environment variables emplaced by the hub, and then they are stored in the artifact's working directory with .trovi.json?

2023-03-29 14:44 UTC, Mark-Powers commented
@super-cooper Yes, if you launch from portal, hub sets some environment variables which are loaded during init here into .trovi.json. It is also stored into .trovi.json if you package a new artifact, etc., rather than storing this in the database.

2023-03-29 14:47 UTC, super-cooper commented
> rather than storing this in the database

WE ARE FINALLY FREE

2023-03-29 15:37 UTC, merged